# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: wasabi
networks:
- id: 1
  start_block: 0
  contracts:
  - name: WasabiOption
    address:
    - 0xFc68f2130e094C95B6C4F5494158cbeB172e18a0
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
    - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
rollback_on_reorg: false
